#!/bin/bash

# Installs the latest vim version from the project's repo (mercurial required).
# Run the script with -h for usage info.

set -e

readonly SCRIPT="$(basename ${BASH_SOURCE})"
default=false
python=("pythoninterp" "python python-dev")
vim_name="vim"
vimpath="/usr/local"

function help() {
  printf "\nUsage: %s [OPTION].\n\n" "${SCRIPT}"
  printf "The following flags are recognized.\n\n"
  printf "     %-10s%-80s\n" '-d' 'Set vim as the default editor.'
  printf "     %-10s%-80s\n" '-h' 'Prints this message.'
  printf "     %-10s%-80s\n" '-n' 'Name to call the vim executable'
  printf "     %-10s%-80s\n" '-p' 'Set a vim installation path. Default: /usr/local.'
  printf "     %-10s%-80s\n" '-P' 'Enable Python 3 support.'
  printf "\nExamples:\n\n"
  printf "     \"%s %s\"     %s\n" "./${SCRIPT}" '-P -n vim3' 'Enable Python 3 support and open editor with vim3.'
  printf "     \"%s %s\"     %s\n" "./${SCRIPT}" '-p $HOME -d' "Install vim in the current user's home directory and make it the default editor"
  exit 1
}

function make_default() {
  local vim_binary="${vimpath}/bin/${vim_name}"
  local editor_path="$(command -v editor)"
  local vi_path="$(command -v vi)"
  local vim_path="$(command -v vim)"
  sudo update-alternatives --install "$editor_path" editor "${vim_binary}" 1
  sudo update-alternatives --set editor "${vim_binary}"
  sudo update-alternatives --install "$vi_path" vi "${vim_binary}" 1
  sudo update-alternatives --set vi "${vim_binary}"
  sudo update-alternatives --install "$vim_path" vim "${vim_binary}" 1
  sudo update-alternatives --set vim "${vim_binary}"

}

while getopts ':dhn:p:P' opt; do
  case "${opt}" in
    d) default=true ;;
    h) help ;;
    n) vim_name="${OPTARG}" ;;
    p) vimpath="${OPTARG}" ;;
    P)
      python[0]="python3interp"
      python[1]="python3 python3-dev"
      ;;
  esac
done

sudo apt-get update 2>&1 >/dev/null
sudo apt-get install -y build-essential ncurses-dev ${python[1]} 2>&1 >/dev/null
if [[ -z "$(command -v hg)" ]]; then
  sudo apt-get install -y mercurial
fi
hg clone https://vim.googlecode.com/hg/ /tmp/vim
cd /tmp/vim/src
./configure \
  --with-features=huge \
  --enable-"${python[0]}" \
  --prefix="${vimpath}" \
  --with-vim-name="${vim_name}" 2>&1 >/dev/null &&
  make 2>&1 >/dev/null &&
  sudo make install 2>&1 >/dev/null
if ${default}; then
  make_default
fi
rm -rf /tmp/vim
