# Personal .zshrc file
# Maintained by Ramces Chirino <http://chirinosky.com>
export ZSH=$HOME/.dotfiles/zsh

for config_file ($ZSH/lib/*.zsh); do
    source $config_file
done

# ==================================================
# General
# ==================================================
setopt INC_APPEND_HISTORY                       # Add entry to history as soon as it's entered.
